{"uuid":"dcf445b2-8937-44e2-a4fb-d5768b3da70e","historyId":"5cd66dbcdf2ef0eefc42c4a71898dbd6","fullName":"test_Cases_Class.Multi_Server_Test_Cases_Class.loginToProductionServer","labels":[{"name":"package","value":"test_Cases_Class.Multi_Server_Test_Cases_Class"},{"name":"testClass","value":"test_Cases_Class.Multi_Server_Test_Cases_Class"},{"name":"testMethod","value":"loginToProductionServer"},{"name":"parentSuite","value":"DFCloudSuite"},{"name":"suite","value":"chrome"},{"name":"subSuite","value":"test_Cases_Class.Multi_Server_Test_Cases_Class"},{"name":"host","value":"Dhiman11"},{"name":"thread","value":"16212@Dhiman11.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Log in to the Production Server and verify successful login.","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"❌ Login failed: ❌ Server is down or unreachable expected [true] but found [false]","trace":"java.lang.AssertionError: ❌ Login failed: ❌ Server is down or unreachable expected [true] but found [false]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertTrue(Assert.java:57)\r\n\tat test_Cases_Class.Multi_Server_Test_Cases_Class.loginToProductionServer(Multi_Server_Test_Cases_Class.java:49)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:580)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1596)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:848)\r\n\tat org.testng.TestRunner.run(TestRunner.java:621)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:443)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)\r\n"},"stage":"finished","steps":[{"name":"Navigating to Production Server URL: https://www33.deepfreeze.com/en/Account/Login","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1752850802204,"stop":1752850802205},{"name":"Login Result: ❌ Server is down or unreachable","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1752850802271,"stop":1752850802271},{"name":"❌ Login failed: ❌ Server is down or unreachable","status":"passed","stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1752850802272,"stop":1752850802272}],"attachments":[],"parameters":[{"name":"os","value":"Windows"},{"name":"browser","value":"chrome"}],"start":1752850802199,"stop":1752850802482}